### ISSUE TITLE
Build for CommonJS?

### ISSUE THREAD

**Issue by seafloyd16** [pmndrs/uikit#100]
I would like to use this library for my Electron app but Electron doesn't support ESM.
How can I build it for CJS, or for browser to work without server?
Thank you.

Windows 10 Home 64bit
NodeJS v18.18.0

**Comment by bbohlender** [comment]
Are you required to use a electron version below v28? Since it seems to be available in electrom >= v28
https://www.electronjs.org/docs/latest/tutorial/esm

**Comment by seafloyd16** [comment]
Thank you. I didn't know that.
But then, should I build it by "npx tsc"?
It gives me over 600 errors.

**Comment by bbohlender** [comment]
I don't see how this question is related to uikit. Probably best to ask it in some electron related community. I would need to check what the proper build setup is.

**Comment by seafloyd16** [comment]
Ah, I'm sorry, I just don't need to build uikit.
But I would like to know if there is a way to build in cjs format.
Thank you.

**Comment by bbohlender** [comment]
uikit is only published via esm. Since esm is the standard today. I recommend configuring your build tool to support esm.

**Comment by seafloyd16** [comment]
Thank you for your help.
I'll migrate my project to ESM.
