### ISSUE TITLE
Examples and Fonts not found

### ISSUE THREAD

**Issue by kwaa** [pmndrs/uikit#102]
It looks like https://pmndrs.github.io/uikit will automatically redirect to https://pmnd.rs/uikit/ and then 404 not found.

Affected URLs:

- https://pmndrs.github.io/uikit/examples/card/
- https://pmndrs.github.io/uikit/examples/dashboard/
- https://pmndrs.github.io/uikit/examples/market/
- https://pmndrs.github.io/uikit/examples/lucide/
- https://pmndrs.github.io/uikit/examples/auth/
- https://pmndrs.github.io/uikit/fonts/inter-light.json
- https://pmndrs.github.io/uikit/fonts/inter-normal.json
- https://pmndrs.github.io/uikit/fonts/inter-medium.json
- https://pmndrs.github.io/uikit/fonts/inter-semi-bold.json
- https://pmndrs.github.io/uikit/fonts/inter-bold.json

![image](https://github.com/user-attachments/assets/d709208c-6623-43e2-8bb5-02627f7d2802)

**Comment by kwaa** [comment]
The fonts are accessible (but having CORS issues with local development) and the example is still 404.

![image](https://github.com/user-attachments/assets/10dc1e57-1eb6-4900-b8f6-fda42b8e4118)

**Comment by bbohlender** [comment]
We had a short DNS issue, but should be fixed now

**Comment by kwaa** [comment]
> We had a short DNS issue, but should be fixed now

It looks like the CORS issue has reappeared (the example doesn't load the fonts correctly either), and it might be better to provide the fonts as an npm package. I can open a feature request if needed.

![image](https://github.com/user-attachments/assets/0a299bf9-c532-4a2e-8bb4-c14a858698bb)

**Comment by bbohlender** [comment]
yes, the team reverted the DNS changes again. But for the future this repo should switch to the default fonts beeing distributed as inlined jsons and base64 encoded textures. If you know how to set those things up (the cicd pipeline needs to run the font conversion and inline the json and the base64 encoded MSDF texture into the uikit package), I'd love to help with a PR :)

**Comment by muhirai** [comment]
So meanwhile how to solve this problem in development? (it seems to work well in Vercel deployment but not in localhost)

**Comment by bbohlender** [comment]
The DNS error is fixed right now and should not appear in the near future, so that everybody can take their time to migrate to 0.4.0 (comming out soon), where this error cannot happen. However, since DNS entries are cached on the OS level, you might need to manually clear the DNS cache or wait a little bit until its fixed again.
