### ISSUE TITLE
Input unfocus function

### ISSUE THREAD

**Issue by ehammons11** [pmndrs/uikit#104]
In InputInternals there is a function that allows the user to force focus:

https://github.com/pmndrs/uikit/blob/e6367b434916a67e842984bebb8b223bca524b4a/packages/react/src/input.tsx#L18-L21

It would be nice if there was another for defocusing. This would allow use cases such as defocusing whenever a user presses the enter key inside of an input.

**Comment by bbohlender** [comment]
enabled in 0.5.4 :)
