### ISSUE TITLE
Custom Font Struggle: Dependecies in "msdf-bmfont-xml"-Tutorial hard to install while the orginal "drei" <Text> won't work

### ISSUE THREAD

**Issue by manuelrossner** [pmndrs/uikit#105]
Thanks for providing uikit, it's a great tool and definetly fills a gap in browser 3D.

For me it's quite hard to use a custom font though: I can't follow the steps in the "Custom Font" tutorial, since it drops errors in seemingly quite old dependencies (node gyp?) that I can't solve.

DonMcCurdy's MSDF Font generator (https://msdf-bmfont.donmccurdy.com/) adds litte errors to my font. Maybe I'm using it wrong, but it looks a bit like spilled over ink in some locations.

Finally trying to fall back to the original <Text> element from "drei" displays beautiful text and easily loads the font, but it won't integrate with the framework. As soon as I wrap it in a <Container> it disappears.

Probably there's good reasons for how uikit is designed, yet I'd be super thankful for hints out of my difficulties!
Thank you so much

**Comment by bbohlender** [comment]
Yes, the tooling we are using is outdated, but there's unfortunately no replacement yet.

My recommendation is to convert your font using fontforge and then use https://msdf-bmfont.donmccurdy.com/ , which should simplify the process while still resolving the little errors in your font :)
