### ISSUE TITLE
Vanilla threejs support?

### ISSUE THREAD

**Issue by marwie** [pmndrs/uikit#11]
Hi, this looks amazing. 

Can the library also be used with vanilla threejs as well?

**Comment by bbohlender** [comment]
No, unfortunately not, its intertwined with R3F.
It can be made to support vanilla, but that's not on the roadmap for the near future (unless somebody financially supports this transition).

**Comment by josephrocca** [comment]
Hey @bbohlender I'm wondering how much financial support is likely required to abstract this so that it works in vanilla three.js? And any guess at a rough ETA if you got solid sponsorship for work on this?
