### ISSUE TITLE
First Layout not working on Next.js (14.2.3)

### ISSUE THREAD

**Issue by its-hmny** [pmndrs/uikit#128]
I'm trying to run  the [first layout](https://pmndrs.github.io/uikit/docs/getting-started/first-layout) work on Next.js version 14.2.3, but I am not able to render anything on the canvas. Everything else R3F related (drei, meshes, texture, loaders etc) is working so I guess there's some kind of problem specifically with `uikit` (version 0.6.2).

The example I'm trying to run is this:
```javascript
export default function App() {
  return (
    <Canvas style={{ position: "absolute", inset: "0", touchAction: "none" }} gl={{ localClippingEnabled: true }}>
      <OrbitControls />
      <Root backgroundColor="red" sizeX={8} sizeY={4} flexDirection="row">
        <Container flexGrow={1} margin={32} backgroundColor="green" />
        <Container flexGrow={1} margin={32} backgroundColor="blue" />
      </Root>
    </Canvas>
  )
}
```

And this is the error I get when trying to render the scene on web browser:

![Screenshot from 2024-10-09 22-53-06](https://github.com/user-attachments/assets/e271d937-77e0-4787-8e05-c99d2dab365c)

Am I missing something?

**Comment by bbohlender** [comment]
this error typically comes from using a outdated threejs version that does not support https://threejs.org/docs/#api/en/core/BufferAttribute.addUpdateRange
