### ISSUE TITLE
Did you mean 'card.js'?

### ISSUE THREAD

**Issue by ajithkumar3005** [pmndrs/uikit#136]
ERROR in ./node_modules/@react-three/uikit-apfel/dist/tab-bar.js 3:0-30
Module not found: Error: Can't resolve './card' in '/Users/abarna/Documents/Virtual Speech/working/New ConfidentoAi/confidentoai/node_modules/@react-three/uikit-apfel/dist'
Did you mean 'card.js'?
BREAKING CHANGE: The request './card' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

The error you're encountering is due to the module resolution rules in a stricter ECMAScript Module environment. It requires the file extensions to be explicitly specified in imports.

To fix this error, try updating the import statements in the tab-bar.js file, adding the .js extension to the unresolved imports. For example:

import './card.js';

**Comment by bbohlender** [comment]
fixed in version 0.6.4 (will release in a second)
