### ISSUE TITLE
Support `node` module resolution

### ISSUE THREAD

**Issue by nyan-left** [pmndrs/uikit#151]
# Issue

Currently `@pmndrs/uikit` fails with `node` module resolution due to `yoga-layout`'s package exports configuration.

Blocked by: https://github.com/facebook/yoga/issues/1760

Once the `yoga-layout` maintainers implement a fix, it would be great to update `@pmndrs/uikit` to incorporate their changes.

## Current Error
```
error TS2307: Cannot find module 'yoga-layout/load' or its corresponding type declarations.
```
This is a tracking issue to implement the fix once available upstream.

**Comment by bbohlender** [comment]
shouldnt module resolution node16 or nodenext be enough. Node 16 isnt even supported anymore, so setting the module resolution to it should be a fine requirement for all your users, right?

**Comment by nyan-left** [comment]
The tricky part is that downstream users may be using `node` resolution for valid reasons, even in modern projects. Supporting `node` resolution would help ensure the library works smoothly in the widest range of build setups without requiring users to adjust their ts configs.

I know `node` resolution isn't recommended anymore (https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node), but the reality is some setups still use it.

**Comment by bbohlender** [comment]
Since the work to support this is on yoga's side, I dont have a strong opinion here, but I honestly would rather tell people to change to recommended settings, then to keep investing time into supporting unsupported configurations while there's still a long roadmap for the library itself. Its not important here, but I wanted to clarify it anyways :D

**Comment by nyan-left** [comment]
Fair enough! 😄 Makes sense to focus on the roadmap - just wanted to raise the compatibility point since I'm running into it. Let's see what the yoga folks say. Thanks for the quick response!

**Comment by nyan-left** [comment]
ts4 support in yoga not planned - https://github.com/facebook/yoga/pull/1764#issuecomment-2561137878
