### ISSUE TITLE
[BUG] Margin does not behave correctly with padding

### ISSUE THREAD

**Issue by WawasCode** [pmndrs/uikit#158]
Margin isn't affected by the padding of other components. In Yoga it works when changing the padding the margin will adjust. 
[Stackblitz](https://stackblitz.com/edit/vitejs-vite-hlvnsqhj?file=src%2FApp.tsx,src%2FContainer.tsx)

**Comment by bbohlender** [comment]
the stack blitz doesnt seem to be working for me

**Comment by WawasCode** [comment]
Can you specify? 
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/360d5d40-2471-468c-a9b3-5f4134377142" />
It works for me

**Comment by bbohlender** [comment]
okay, just took ages to load for me :D
can you elaborate what you suspect is not correct. For me everything seems fine

**Comment by WawasCode** [comment]
When you increase the padding of the blue container the red container doesn't move so the margin to it stays correct. The red one starts overlapping. I tried it in yoga something as follows:
```     
<Node>
        <Node style={{height: 40, width: 40, padding: 90}} />
        <Node style={{height: 40, width: 40, marginTop: 30}} />
        <Node style={{height: 40, width: 40}} />
        <Node style={{height: 40, width: 40}} />
</Node>
    ```
If I increase the padding from the 1. Node the bottom nodes will move so the margin stays correct. In UIKit this doesn't happen.

```
<Container alignItems="center" justifyContent="center">
        <Container backgroundColor={'blue'} padding={40} /> //increase padding
        here
        <Container
          width={14 * 2}
          padding={20}
          positionType="absolute"
          marginTop={14 * 0.5}
          transformTranslateY={14 + 20}
          backgroundColor={'red'}
        />
      </Container>
```
If I increase the Padding the blue container will start to overlap with the red one.

**Comment by bbohlender** [comment]
not sure how these 2 examples compare since you are using positionType="absolute" for the second Container

please showcase the issue without using position absolute, or showcase the issue in yoga also using position absolute.

In general uikit does almost 0 interference with these properties and directly forwards them to yoga, so its rather unlikely that there's a difference to yoga

**Comment by WawasCode** [comment]
Ok I understand I just misunderstood. I should have added an extra container and then align the items there. the absolute broke it. Sorry :)

**Comment by bbohlender** [comment]
absolutely no problem! :)
