### ISSUE TITLE
Yoga dep error when running in expo-web/react-native-web

### ISSUE THREAD

**Issue by Seanmclem** [pmndrs/uikit#17]
Hi, I have a repository here: [https://github.com/Seanmclem/r3f-uikit-ts-expo](https://github.com/Seanmclem/r3f-uikit-ts-expo)

Where I have set up a basic Expo/RN app with web. I tested a basic html hello world, then dropped in the demo from the docs intro. Which works fine in a [Vite/web repo](https://github.com/Seanmclem/r3f-uikit-vite-ts) I also made. 

When running the web app via `npm run web` I get this on the terminal.
> `Unable to resolve "yoga-layout/wasm-async" from "node_modules/@react-three/uikit/dist/text/react.js"`

And after installing expo-gl, and running `npm run ios`, I also get the exact same error. 

What can I do? Or is there something you can do on your end?

Thanks for reading. 

--Sean

**Comment by bbohlender** [comment]
Hey, I've started a branch feature/expo and spent too much time on it because pnpm monorepo and expo don't really like each other.
I got it running on web and android. However, expo-gl has incorrectly implemented the OpenGL ES 3 call to bufferSubData which three.js needs for updating buffer attributes, which is heavily used in uikit for instancing, so the rendering looks incorrect on android.
Help in that direction is very much appreciated, since I don't want to invest much more time in fixing expo-gl and figuring out why ios crashes.

**Comment by MaxTwentythree** [comment]
Hi, I got a similar issue with wasm-async. I get this error when trying to use uikit:

> Uncaught Error: Cannot find module 'yoga-layout/wasm-async'

I'm on the newest versions for react, r3f and three.
I also tried yoga-layout directly but no change.

I'm on a pretty old node version though (node 14.21.3) .. have to be unfortunatelly .. might this be the cause?

**Comment by bbohlender** [comment]
@MaxTwentythree if you are also using expo like the original issue, then check out this issue #16 

If not, the error comes from your bundler / node not supporting package.json exports field, which is a more or less recent addition to the spec. So updating node might do the trick

**Comment by MaxTwentythree** [comment]
Hi @bbohlender ,
thanks for your quick reply.. yeah I thought so.
I hope I can update node soon when the base framework I use (meteor.js) finally supports newer node versions.
I will report back when the node update fixes the problem!
Or might try it in a new project when I find the time.
Thanks anyways! :)

**Comment by bbohlender** [comment]
@MaxTwentythree
Ah, your bundler is meteor.js
I am not familiar, but a quick Google tells me that they do not support the exports field in package.json, which leads to issues with multiple libraries

https://github.com/meteor/meteor/discussions/11727
https://forums.meteor.com/t/how-to-import-npm-package-with-exports-field-in-package-json/57276
