### ISSUE TITLE
hitbox for close X in modal is tiny

### ISSUE THREAD

**Issue by jmatsushita** [pmndrs/uikit#23]
Hi there,

I'm attaching a video showing that [in the dashboard example](https://pmndrs.github.io/uikit/examples/dashboard/) after opening the "Edit Profile" link at the top right, when I move the cursor on the close X icon at the top right of the modal, it's quite difficult to hit the right spot

https://github.com/pmndrs/uikit/assets/356097/9cde2165-31ee-4ea9-a5e7-d09dc5238897

**Comment by bbohlender** [comment]
Fix in 2a28f5b
