### ISSUE TITLE
expo web 

### ISSUE THREAD

**Issue by jmatsushita** [pmndrs/uikit#24]
Hi,

Running `expo install react-native-web` in [my fork's `expo-yarn` branch ](https://github.com/jmatsushita/uikit/tree/feature/expo-yarn) and `yarn start` followed by the `w` key, correctly starts the browser and seems quite close to a functional uikit for web output, except for these details:
 - some white space at the top
 - buttons can't be clicked (unless moving the mouse while holding click) 
 - scrolling with the wheel or swiping on a touchpad doesn't work

UPDATE: comparing more closely to the original [example](https://pmndrs.github.io/uikit/examples/market/) I think that the cursor doesn't change to the hover icon on buttons either.

<img width="975" alt="image" src="https://github.com/pmndrs/uikit/assets/356097/29d07978-7f7f-4e3c-ba54-9ae6330640c9">

**Comment by jmatsushita** [comment]
> once we have webgpu support

Hi @bbohlender I was looking into your library again and was wondering about whether there's any momentum towards using webgpu? It looks like https://github.com/wcandillon/react-native-webgpu supports @react-three/fiber so I'm wondering whether that would possibly be a new building block?

**Comment by bbohlender** [comment]
Hey @jmatsushita 
Yes I will be moving towards a tsl implementation for all the shaders to support webgpu so react native support will possible with that!
