### ISSUE TITLE
positioning should not be applied when static

### ISSUE THREAD

**Issue by patrickkeenan** [pmndrs/uikit#25]
I'm not certain about this. but positionLeft, positionRight, positionTop, and positionBottom probably shouldn't be applied if the positionType is static, otherwise they're kinda like padding right?

**Comment by bbohlender** [comment]
That's completly handled by yoga, so we don't have influence over that, but it might be fixed/different in yoga 3.0 which we will upgrade to soon :)

**Comment by bbohlender** [comment]
I'll close this for now since it falls in the area of responsibility of yoga
