### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'morphAttributes')

### ISSUE THREAD

**Issue by clearly-outsane** [pmndrs/uikit#29]
In Next.js (14.1.3) , I have 
`<Root backgroundColor='red' sizeX={2} sizeY={1} flexDirection='row'>
          <Container flexGrow={1} margin={48} backgroundColor='green' />
          <Container flexGrow={1} margin={48} backgroundColor='blue' />
</Root>`

This is in a project cloned off of the r3f-next-starter which is part of pmndrs. when I put this in a <Three> tag the project just crashes. I have no idea why.

**Comment by bbohlender** [comment]
@clearly-outsane The error is fixed in the latest version (v0.1.22)

![Screenshot 2024-03-26 at 10 16 16](https://github.com/pmndrs/uikit/assets/85560643/d2f07830-fb1e-4b8f-aea1-17da9a9ed4ac)
