### ISSUE TITLE
Relative paths on font family provider

### ISSUE THREAD

**Issue by cyango** [pmndrs/uikit#31]
Right now font family provider seems to only work with absolute paths. I think it's more convenient to have relative paths for many reasons (react relative paths builds, etc).

Suggestion to be loaded on react public folder:

`
      <FontFamilyProvider
        roboto={{
          medium: "./fonts/GilroySemiBold-msdf/GilroySemiBold-msdf.json",
          bold: "./fonts/PolySansBulkyWide-msdf/PolySansBulkyWide-msdf.json",
        }}
      >
...
      </FontFamilyProvider>
`

**Comment by cyango** [comment]
I'm not sure, but changes can be made in here?

`export function loadCachedFont(url: string, renderer: WebGLRenderer, onLoad: (font: Font) => void): void {

//manipulate url here using process.env.PUBLIC_URL ??

  let entry = fontCache.get(url)
  if (entry instanceof Set) {
    entry.add(onLoad)
    return
  }
  if (entry != null) {
    onLoad(entry)
    return
  }
...
`

**Comment by bbohlender** [comment]
Implemented in v0.2.6 (808cf09)
