### ISSUE TITLE
Yoga fails in StrictMode when manually rendering canvas

### ISSUE THREAD

**Issue by Ledzz** [pmndrs/uikit#35]
Hello!
Firstly, thank you for your work on this library. We've been watching for its development and we want to integrate it to our project in future.
But we encountered some bug that we don't know how to fix.
This issue appears when using react's StrictMode and rendering the root without canvas. Please see the attached repro:
https://stackblitz.com/edit/vitejs-vite-wfq5n8?file=src%2Fmain.tsx

**Comment by bbohlender** [comment]
@Ledzz glad to see you here. The issue should be fixed in the latest version (0.2.8)

**Comment by Ledzz** [comment]
Thank you! Could please you briefly explain what was the issue?

**Comment by bbohlender** [comment]
For sure.
Basically, doing the following is not what React likes
```jsx
function Component() {
  const resource = useMemo(() => createResource(), [])
  useEffect(() => () => destroy(resource), [resource])
}
```

to some degree this is awesome, but figuring out a performant pattern to create resources and clean them up was a bit of a struggle I solved in the latest rewrite.

The way it's now setup is the following
```jsx
function Component() {
  const resource = useMemo(() => setupResource(), [])
  useEffect(() => {
    const destroy = resource.init()
    return destroy
  }, [resource])
}
```

**Comment by Ledzz** [comment]
wow, thank you! typical react moment 🫠
