### ISSUE TITLE
Cannot install components via CLI

### ISSUE THREAD

**Issue by manspaniel** [pmndrs/uikit#47]
Running `npx uikit component add apfel button` currently prints an error:
> Unable to fetch registry for apfel kit: Unexpected token : in JSON at position 3

(This was working a few hours ago)

After some troubleshooting, I can see that the CLI is requesting:

https://raw.githubusercontent.com/pmndrs/uikit/main/packages/kits/apfel/registry.json, which is a 404.

The URL is missing the `src` directory. This works:

https://raw.githubusercontent.com/pmndrs/uikit/main/packages/kits/apfel/src/registry.json

**Comment by bbohlender** [comment]
same as #46 
Thanks for reporting anyways, fix for now is the same as in #46 
will work with 0.3.0 again

**Comment by bbohlender** [comment]
@manspaniel should be fixed now in 0.3.0 :)
