### ISSUE TITLE
Retained mode UI example

### ISSUE THREAD

**Issue by munrocket** [pmndrs/uikit#50]
This may sound stupid but I want alternative to immediate mode UI, because I suppose it will be faster for my case. Is it possible to render UI in texture?

**Comment by bbohlender** [comment]
For sure, just render the UI it to a framebuffer (e.g. RenderTexture from @react-three/drei)

**Comment by munrocket** [comment]
Thanks for example 🤗

**Comment by munrocket** [comment]
@bbohlender examples are laggy with scroll on modern iPhone, that is why I am asking.

Your render is CPU bound, you have ~7500 commands where ~7300 just `bufferSubData()` that can be joined.

<img width="434" alt="3" src="https://github.com/pmndrs/uikit/assets/20033246/90e489ea-ec8b-4923-8ea6-f169be8276db">

**Comment by bbohlender** [comment]
@munrocket joining the buffer writes is on the to-do list. However, currently, to reduce buffer modifications, the glyphs of each text field fill up all available space, leading to possible fragmentation of one text field into different parts of the buffer. Therefore, I was waiting with joining the buffer writes until I have a better glyph-buffer allocation strategy that balances the number of modifications and fragmentization
