### ISSUE TITLE
No way to load font when hashing filename

### ISSUE THREAD

**Issue by Ledzz** [pmndrs/uikit#52]
I'm using vite to build the application, and it's adding file hashes to filenames for cache busting. It's very common to do it for fonts, but I'm doing it anyway to always make sure I can update fonts asap.
It is impossible now to use fonts, because font png url is taken from font json definition.
I've already fixed it locally and would like to make a PR with changes.

**Comment by bbohlender** [comment]
hmmm, thanks for the PR. I am not a fan of seperating json and png. I'd actually rather preferred it if the image was base64 encoded into the json. I know that this would require some build time tooling, but imo it would be the much cleaner solution with a better DX. What do you think?

**Comment by Ledzz** [comment]
Sounds reasonable. I'll try to do it on monday. I believe we still need some fix to make it work? I'll redo my PR.

**Comment by bbohlender** [comment]
if we use data urls it should not require any change, but you'd have to test it :)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

if you come up with a process / tool to move the image into the json, it would be awesome if you could document that in the uikit docs :)

**Comment by Ledzz** [comment]
@bbohlender you're right, it works. I just thought that there will be some url composing logic that interferes using data urls. Made a PR with a sample script to do it: #56

**Comment by bbohlender** [comment]
@Ledzz thanks for the PR, script looks very nice. Eventually, I want the font file generation to be integrated into the pmndrs/uikit CLI, where I would also inline the texture by default :)
