### ISSUE TITLE
Fix importing from `./theme.js` to be from `./theme` in generated code

### ISSUE THREAD

**Issue by nirtamir2** [pmndrs/uikit#55]
Hi
I tried uikit and run the command

```bash
npx uikit component add apfel card
```

The generated file includes a reference to `theme.js`, which does not exist since the code generates `theme.tsx`. It would be better to remove the `.js` suffixes from the utils and import them from `./theme`, ensuring that the user doesn't need to make any adjustments to integrate it.

https://github.com/pmndrs/uikit/blob/465c14a59bb1166c6403c9057baf5e0eb0a20bf6/packages/kits/default/src/card.tsx#L3

https://github.com/search?q=repo:pmndrs/uikit%20from%20%22./theme.js%22&type=code

**Comment by bbohlender** [comment]
> It would be better to remove the .js suffixes from the utils and import them from ./theme

This is true for older versions of js/ts (which you might be forced to use with something like next.js), but in newer versions of js/ts, file extensions are preferred and partially necessary:

> Relative import paths need full extensions (we have to write import "./foo.js" instead of import "./foo").
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#type-in-packagejson-and-new-extensions 

I might start working on a CLI that asks the user/detects the preferred js/ts style, but I also hope tools and users move towards the new ESM standard so libraries can stop supporting to standards.
