### ISSUE TITLE
Z-Index issue

### ISSUE THREAD

**Issue by Ledzz** [pmndrs/uikit#58]
Please see the repro: https://stackblitz.com/edit/vitejs-vite-jvlwa4?file=src%2Fmain.tsx
**Expected result**: text "Demo" has grey background
**Actual result**: the text background is under the image

Ofc setting zIndexOffset helps, but is there any way to avoid it?

**Comment by bbohlender** [comment]
I guess you wanted a different solution, but that's always the best for uikit (explicit parent/child relations)
https://stackblitz.com/edit/vitejs-vite-bptccl?file=src%2Fmain.tsx

siblings are treated as unordered to improve performance by giving the buffer allocation strategy freedom in rearranging them
