### ISSUE TITLE
Visibility hidden not working for children

### ISSUE THREAD

**Issue by Ledzz** [pmndrs/uikit#59]
Please see the repro: https://stackblitz.com/edit/vitejs-vite-npxuu4?file=src%2Fmain.tsx
**Expected result:** Text "Demo" is not visible
**Actual result:** Text is visible

**Comment by bbohlender** [comment]
@Ledzz that behavior is expected, yes, in html "visibility" and a bunch of other properties inherit those values to their children by default. This is not (yet) the case in uikit, which is one of the reasons "DefaultProperties" exists.

corrected version using "DefaultProperties"
https://stackblitz.com/edit/vitejs-vite-xvfyn6?file=src%2Fmain.tsx
