### ISSUE TITLE
[Docs] "Vanilla Three.js" tab disappears when other tabs selected

### ISSUE THREAD

**Issue by jontonsoup4** [pmndrs/uikit#61]
# Description

On the uikit docs website, the "Vanilla Three.js" tab inside of the "GETTING STARTED" category disappears when selecting a few other tabs. The tabs that seem to effect the "Vanilla Three.js" tab are "Components and Properties" within the "GETTING STARTED" category, and the "Apfel" and "Default" tabs in the "KITS" category. All other tabs show the "Vanilla Three.js" tab as expected.

## Steps to recreate

* Navigate to https://docs.pmnd.rs/uikit/getting-started/introduction
* Click "First Layout" tab
* This will show the "Vanilla Three.js" tab at the bottom of the "GETTING STARTED" category
* Now select "Components and Properties"
* The "Vanilla Three.js" tab will disappear
* Repeat with "Apfel" and "Default", as those hide the "Vanilla Three.js" tab as well

### Expected 
<img width="257" alt="Screenshot 2024-05-22 at 2 25 04 PM" src="https://github.com/pmndrs/uikit/assets/15053417/67fded7d-0a5f-4440-b6e4-1f14c0c221be">

### Actual
<img width="260" alt="Screenshot 2024-05-22 at 2 25 17 PM" src="https://github.com/pmndrs/uikit/assets/15053417/a588badb-c3d8-4c6e-8dff-0b6088555c1f">

**Comment by bbohlender** [comment]
Thanks for reporting.
@CodyJasonBennett Do you have a clue what is happening here. I am actually not sure how vercel/next is doing the revalidation of the docs content for https://github.com/pmndrs/website/tree/docs

**Comment by bbohlender** [comment]
@jontonsoup4 docs are now correctly synced thanks to Cody :)
