### ISSUE TITLE
can't start project

### ISSUE THREAD

**Issue by devDoubleH** [pmndrs/uikit#9]
pnpm dev

> @ dev /Users/ismoiljonabdukakhkhorov/Desktop/uikit/examples/dashboard
> vite --host

  VITE v5.0.12  ready in 135 ms

  ➜  Local:   https://localhost:5173/
  ➜  Network: https://10.20.6.26:5173/
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "./wasm.js"

    ../../packages/uikit/src/flex/load-base64.ts:2:23:
      2 │ import { base64 } from './wasm.js'
        ╵                        ~~~~~~~~~~~

✘ [ERROR] Could not resolve "./setter.js"

    ../../packages/uikit/src/flex/node.ts:14:23:
      14 │ import { setter } from './setter.js'
         ╵                        ~~~~~~~~~~~~~

**Comment by bbohlender** [comment]
It seems the initial setup script didn't run successfully.
Did any of the initial setup scripts fail

`pnpm install`  
`pnpm -r inline-wasm`  
`pnpm -r convert`  
`pnpm -r generate`  
`pnpm -r build`

**Comment by bbohlender** [comment]
Feel free to reopen if the bug the issue is still there (use the current instructions in the readme)
