### ISSUE TITLE
React Native failed ios build @react-three/uikit

### ISSUE THREAD

**Issue by slyduda** [pmndrs/uikit#97]
Getting `Unable to resolve "@pmndrs/uikit/internals" from "node_modules/@react-three/uikit/dist/container.js"` when building for ios with expo. When installing @pmndrs/uikit my react native project gets stuck at Pod install. I have seen others successfully use the package without @pmndrs/uikit as is also explained in the docs. Is this a known native issue?

**Comment by slyduda** [comment]
found this! feel free to close. for some reason i thought expo was working with this package. https://github.com/pmndrs/uikit/issues/17#issuecomment-1992701847

**Comment by bbohlender** [comment]
I'll close this for now, but I'll keep looking into this once we have webgpu support in pmndrs/uikit :)
