### ISSUE TITLE
Issues with the vanilla docs

### ISSUE THREAD

**Issue by graemeniedermayer** [pmndrs/uikit#99]
https://docs.pmnd.rs/uikit/getting-started/vanilla

There's a number of small fixes needed for the documentation.

1. in the `index.html` file, `root` needs to be a `canvas` not a `div`.
2.  

```
const root = new Root(camera, renderer, undefined, {
    flexDirection: "row",
    padding: 10,
    gap: 10
})
```

should be something more like

```
const root = new Root(camera, renderer,  {
  flexDirection: 'row',
  gap: 30,
  width: 500,
  borderRadius: 10,
  padding: 10,
  alignItems: 'center',
  backgroundColor: 'red',
  overflow: 'scroll',
})
```

(Some of these options might be unnecessary but the first one created a ui that wasn't visible.)

The example here works much better than the documentation. 
https://github.com/pmndrs/uikit/tree/main/examples/vanilla

**Comment by bbohlender** [comment]
Thanks, would you like to fix them in a PR? :)

**Comment by bbohlender** [comment]
fixed in latest release
